// Generated by `npm run poster` from the real camera and scene. Do not edit.
import type { AnchorId, Variant } from "./bus";

export const ANCHORS: Record<Variant, Record<AnchorId, { x: number; y: number }>> = {
  wide: {
    content: { x: 13.9, y: 17 },
    audience: { x: 34.2, y: 28.8 },
    trends: { x: 67.6, y: 24.2 },
    deals: { x: 84.1, y: 29 },
    perf: { x: 58.4, y: 29.2 },
    mark: { x: 50, y: 23.2 },
  },
  tall: {
    content: { x: 27.5, y: 32.1 },
    audience: { x: 44.2, y: 36.4 },
    trends: { x: 64.2, y: 33.8 },
    deals: { x: 67.2, y: 42.2 },
    perf: { x: 56.5, y: 42.7 },
    mark: { x: 50, y: 25.9 },
  },
};
