import type { AnchorId, Variant } from "./bus";

/** Stage sizes. The poster, the canvas and the chips all share one box with this aspect ratio, so a chip placed at a
 * percentage lines up with the same point in the poster and in the live scene. Poster pixel sizes: wide 1600x1000, tall 900x1200. */
export const STAGE_ASPECT: Record<Variant, number> = { wide: 1.6, tall: 0.75 };

/** Where each chip sits, as a percentage of the stage (x from the left, y from the top). Regenerated by `npm run poster`
 * from the real camera and scene. These are placeholder values until the first generation. */
export const ANCHORS: Record<Variant, Record<AnchorId, { x: number; y: number }>> = {
  wide: {
    content: { x: 16, y: 31 },
    audience: { x: 39, y: 34 },
    trends: { x: 65, y: 27 },
    deals: { x: 86, y: 41 },
    perf: { x: 58, y: 39 },
    mark: { x: 50, y: 30 },
  },
  tall: {
    content: { x: 24, y: 36 },
    audience: { x: 44, y: 41 },
    trends: { x: 70, y: 33 },
    deals: { x: 78, y: 50 },
    perf: { x: 56, y: 47 },
    mark: { x: 50, y: 38 },
  },
};
