// Writes src/app/backdrop.css: the small images behind the page, as CSS custom properties.
// Run: node scripts/backdrop.mjs
//
//   --mask-far / --mask-near   a treeline in two layers (soft far hills; a nearer ridge with conifers and round trees).
//                              Used as CSS masks, so the page paints them in whatever colour its theme asks for.
//                              Every curve is a sum of whole sine periods, so the tile repeats with no seam.
//   --stars-a / --stars-b      two still star fields of different size, layered so the repeat is hard to see (dark theme only).
//   --paper-light / --paper-dark   a fine paper grain, dark specks on cream and pale specks on indigo.
//
// Everything is deterministic: run it twice and the file is identical.
import { writeFileSync } from "node:fs";

function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const TAU = Math.PI * 2;
const f1 = (n) => Math.round(n * 10) / 10;
const uri = (svg) => `url("data:image/svg+xml,${encodeURIComponent(svg)}")`;

const W = 2400; // tile width in tile units
const H = 200;

/** A ridge that repeats exactly once per tile: a sum of sine waves with whole numbers of periods. */
function ridge(base, comps, seed) {
  const r = rng(seed);
  const parts = comps.map(([k, a]) => ({ k, a, p: r() * TAU }));
  const y = (x) => base - parts.reduce((s, c) => s + c.a * Math.sin((TAU * c.k * x) / W + c.p), 0);
  return y;
}
const ridgePath = (y) => {
  const pts = [];
  for (let x = 0; x <= W; x += 20) pts.push(`${x} ${f1(y(x))}`);
  return `M0 ${H}L${pts.join("L")}L${W} ${H}Z`;
};

function pine(x, y, h) {
  const w = h * 0.21;
  const p = (dx, dy) => `${f1(x + dx * w)} ${f1(y - dy * h)}`;
  return `M${p(0, 1)}L${p(0.5, 0.64)}L${p(0.22, 0.64)}L${p(0.8, 0.34)}L${p(0.3, 0.34)}L${p(1, 0.06)}L${p(0.1, 0.06)}L${p(0.1, 0)}L${p(-0.1, 0)}L${p(-0.1, 0.06)}L${p(-1, 0.06)}L${p(-0.3, 0.34)}L${p(-0.8, 0.34)}L${p(-0.22, 0.64)}L${p(-0.5, 0.64)}Z`;
}

function treeline(seed) {
  const r = rng(seed);
  const far = ridge(122, [[1, 26], [2, 19], [3, 12], [5, 7], [8, 4]], seed + 1);
  const near = ridge(166, [[2, 13], [3, 10], [5, 7], [9, 4], [13, 2.5]], seed + 2);
  const grove = ridge(0, [[3, 1], [5, 0.8], [7, 0.5]], seed + 3); // where trees gather
  let paths = ridgePath(near);
  let blobs = "";
  for (let x = 36; x < W - 36; x += 16 + r() * 30) {
    if (grove(x) < -0.55 && r() < 0.8) continue; // clearings
    const base = near(x) + 5;
    if (r() < 0.22) {
      const rx = 8 + r() * 8;
      blobs += `<rect x="${f1(x - 1.4)}" y="${f1(base - rx * 1.5)}" width="2.8" height="${f1(rx * 1.5)}"/><ellipse cx="${f1(x)}" cy="${f1(base - rx * 1.6)}" rx="${f1(rx)}" ry="${f1(rx * 1.15)}"/>`;
    } else {
      paths += pine(x, base, 30 + r() * 46);
    }
  }
  const svg = (d, extra = "") => `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><path d="${d}"/>${extra}</svg>`;
  return { far: svg(ridgePath(far)), near: svg(paths, blobs) };
}

function stars(w, h, count, seed, big) {
  const r = rng(seed);
  let out = "";
  for (let i = 0; i < count; i++) {
    const x = f1(r() * w), y = f1(r() * h);
    const bright = r() < big;
    const rad = bright ? 1.2 + r() * 0.6 : 0.5 + r() * 0.55;
    const o = f1(bright ? 0.7 + r() * 0.25 : 0.28 + r() * 0.4);
    if (bright) out += `<circle cx="${x}" cy="${y}" r="${f1(rad * 2.6)}" fill="#fff" fill-opacity="0.09"/>`;
    out += `<circle cx="${x}" cy="${y}" r="${f1(rad)}" fill="#fff" fill-opacity="${o}"/>`;
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">${out}</svg>`;
}

const paper = (matrix) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="240" height="240"><filter id="n" x="0" y="0" width="100%" height="100%"><feTurbulence type="fractalNoise" baseFrequency=".8" numOctaves="2" seed="7" stitchTiles="stitch"/><feColorMatrix values="${matrix}"/></filter><rect width="100%" height="100%" filter="url(#n)"/></svg>`;

const tl = treeline(41);
const css = `/* Generated by scripts/backdrop.mjs. Edit the script, not this file. */
:root {
  --mask-far: ${uri(tl.far)};
  --mask-near: ${uri(tl.near)};
  --stars-a: ${uri(stars(360, 300, 17, 5, 0.18))};
  --stars-b: ${uri(stars(590, 470, 24, 9, 0.1))};
  --paper-light: ${uri(paper("0 0 0 0 .1  0 0 0 0 .12  0 0 0 0 .04  0 0 0 .075 0"))};
  --paper-dark: ${uri(paper("0 0 0 0 .85  0 0 0 0 .88  0 0 0 0 1  0 0 0 .06 0"))};
}
`;
writeFileSync(new URL("../src/app/backdrop.css", import.meta.url), css);
console.log(`src/app/backdrop.css: ${css.length} bytes`);
