// Writes src/app/wind.css: keyframes for the scene's trees, sampled from a small physics model.
// Run: node scripts/wind.mjs
//
// One gust cycle is shared by every tree, so the wind stays one wind. Each tree is a damped spring pushed by that wind:
// tall trees answer slowly and swing further, small ones answer quickly and settle sooner. The page delays each tree by
// its distance from the left edge, so a gust crosses the scene from left to right, the way the clouds drift.
// A second, faster loop (flutter) adds the small restless movement of branches and leaves.
import { writeFileSync } from "node:fs";

const GUST = 24; // seconds per gust cycle
// A gust centred at c (s) with half-width w (s), repeated every cycle.
const g = (t, c, w) => [-1, 0, 1].reduce((s, k) => s + Math.exp(-((((t % GUST) - c - k * GUST) / w) ** 2)), 0);
const TAU = Math.PI * 2;
// Wind speed over one cycle: a steady breeze, three gusts of different strength and length, and a little turbulence.
// Every term repeats exactly once per cycle, so the loop has no seam.
const wind = (t) =>
  0.16 +
  0.45 * g(t, 0.12 * GUST, 2.6) +
  1.0 * g(t, 0.42 * GUST, 3.4) +
  0.25 * g(t, 0.5 * GUST, 1.4) +
  0.55 * g(t, 0.75 * GUST, 2.8) +
  0.06 * Math.sin((TAU * 9 * t) / GUST + 0.3) +
  0.045 * Math.sin((TAU * 14 * t) / GUST + 1.7);

/** Lean of a damped spring with natural period `period` (s) and damping ratio `zeta`, after it has settled into the loop. */
function respond(force, loop, period, zeta) {
  const w = TAU / period;
  const dt = 1 / 1000;
  let x = force(0);
  let v = 0;
  const out = [];
  const cycles = 6;
  const steps = Math.round((cycles * loop) / dt);
  for (let i = 0; i <= steps; i++) {
    const t = i * dt;
    v += (w * w * (force(t) - x) - 2 * zeta * w * v) * dt;
    x += v * dt;
    if (t >= (cycles - 1) * loop - 1e-9) out.push([t - (cycles - 1) * loop, x]);
  }
  return out;
}

/** Ramer-Douglas-Peucker: keep only the samples needed to stay within `eps` of the curve (in normalised units). */
function simplify(pts, eps) {
  if (pts.length < 3) return pts;
  const [a, b] = [pts[0], pts[pts.length - 1]];
  let worst = 0;
  let at = 0;
  for (let i = 1; i < pts.length - 1; i++) {
    const [t, y] = pts[i];
    const lerp = a[1] + ((b[1] - a[1]) * (t - a[0])) / (b[0] - a[0]);
    const d = Math.abs(y - lerp);
    if (d > worst) [worst, at] = [d, i];
  }
  if (worst <= eps) return [a, b];
  return [...simplify(pts.slice(0, at + 1), eps).slice(0, -1), ...simplify(pts.slice(at), eps)];
}

/** Keyframes that rotate by `deg` at the curve's peak. Amplitudes are baked in (no CSS variables), so the browser can run
 *  the animation on the compositor without restyling the page every frame. */
function keyframes(name, curve, loop, deg) {
  const peak = Math.max(...curve.map(([, y]) => Math.abs(y)));
  let pts = curve.filter((_, i) => i % 10 === 0).map(([t, y]) => [t, y / peak]);
  pts[pts.length - 1] = [loop, pts[0][1]]; // close the loop exactly
  pts = simplify(pts, 0.012);
  const seen = new Set();
  const frames = pts
    .map(([t, y]) => [+((100 * t) / loop).toFixed(1), +(y * deg).toFixed(2)])
    .filter(([pct]) => !seen.has(pct) && seen.add(pct))
    .map(([pct, a]) => `${pct}%{rotate:${a}deg}`);
  return { css: `@keyframes ${name}{${frames.join("")}}`, n: frames.length };
}

// Peak lean in degrees by tree size (t tall, m medium, s small). Broadleaf trunks are stiffer, their crowns looser.
const LEAN = { t: 2.6, m: 3.0, s: 3.4 };
const KIND = { c: 1, b: 0.7 };
const FLUTTER_DEG = { c: 0.8, b: 1.8 };

// Local turbulence for branches and leaves: three incommensurate wobbles inside a 10 s loop.
const FLUTTER = 10;
const flutterCurve = Array.from({ length: 10001 }, (_, i) => {
  const t = (i / 10000) * FLUTTER;
  return [t, 0.55 * Math.sin((TAU * 3 * t) / FLUTTER + 0.4) + 0.3 * Math.sin((TAU * 5 * t) / FLUTTER + 2.1) + 0.2 * Math.sin((TAU * 8 * t) / FLUTTER + 5.2)];
});

const blocks = [];
const report = [];
for (const [size, period, zeta] of [["t", 3.2, 0.32], ["m", 2.5, 0.36], ["s", 1.8, 0.42]]) {
  const curve = respond(wind, GUST, period, zeta);
  for (const kind of ["c", "b"]) {
    const k = keyframes(`gust-${size}-${kind}`, curve, GUST, LEAN[size] * KIND[kind]);
    blocks.push(k.css);
    report.push(`gust-${size}-${kind}: ${k.n} keyframes`);
  }
}
for (const kind of ["c", "b"]) {
  const f = keyframes(`flutter-${kind}`, flutterCurve, FLUTTER, FLUTTER_DEG[kind]);
  blocks.push(f.css);
  report.push(`flutter-${kind}: ${f.n} keyframes`);
}

const header = `/* Generated by scripts/wind.mjs from a damped-spring wind model. Edit the script, not this file. */\n`;
writeFileSync(new URL("../src/app/wind.css", import.meta.url), header + blocks.join("\n") + "\n");
console.log(report.join("\n"));
